from django.db import models
import datetime

# Create your models here.

B_OR_S = (
			('Berserker', 'Berserker'),
			('Shieldmaiden', 'Shieldmaiden')
		)

class Ambassador(models.Model):
	name = models.CharField("Ambassador Name*", max_length = 40)
	about = models.TextField("About*", max_length = 2000)
	berserker_or_shieldmaiden = models.CharField("Berserker or Shieldmaiden*?", max_length = 12, choices = B_OR_S)
	image = models.ImageField("Profile Picture", upload_to='media/', null=True)
	
	ambassador_start = models.DateField("Date They Became an Ambassador*", default = datetime.date.today)
	ambassador_end = models.DateField("Date They Were no Longer an Ambassador", null = True, blank = True, help_text = "Leave blank if they're still an ambassador")
	still_an_ambassador = models.BooleanField("Still an Ambassador?", default = True)
	is_featured = models.BooleanField("Would you like them Featured?", default = True)
	
	def __str__(self):
		return self.name
			
	def save(self): # For all autogenerated values
		if not self.ambassador_end:
			self.still_an_ambassador = True
		else:
			self.still_an_ambassador = False
		super(Ambassador, self).save()