# Generated by Django 2.0.4 on 2018-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=40, verbose_name='Subscriber Name')),
                ('s_email', models.EmailField(max_length=85, verbose_name='Subscriber Email')),
            ],
        ),
    ]
