# Generated by Django 2.0.4 on 2018-05-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='wants_help',
            field=models.BooleanField(default=False, verbose_name='Fitness Counseling'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='wants_newsletter',
            field=models.BooleanField(default=True, verbose_name='Newsletter Signup'),
        ),
    ]
