# Generated by Django 2.0.4 on 2018-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Ambassador Name')),
                ('about', models.TextField(max_length=2000, verbose_name='About')),
                ('berserker_or_shieldmaiden', models.CharField(choices=[('Berserker', 'B'), ('Shieldmaiden', 'S')], max_length=1, verbose_name='Berserker or Shieldmaiden?')),
            ],
        ),
    ]
