# Generated by Django 2.0.4 on 2018-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='berserker_or_shieldmaiden',
            field=models.CharField(choices=[('Berserker', 'ererer'), ('Shieldmaiden', 'ggss')], max_length=12, verbose_name='Berserker or Shieldmaiden?'),
        ),
    ]
