# Generated by Django 2.0.4 on 2018-05-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0002_auto_20180505_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='berserker_or_shieldmaiden',
            field=models.CharField(choices=[('Berserker', 'Berserker'), ('Shieldmaiden', 'Shieldmaiden')], max_length=12, verbose_name='Berserker or Shieldmaiden?'),
        ),
    ]
