# Generated by Django 2.0.4 on 2018-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0006_auto_20180505_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
