# Generated by Django 2.0.4 on 2018-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0007_ambassador_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='image',
            field=models.ImageField(null=True, upload_to='ironviking/media', verbose_name='Profile Picture'),
        ),
    ]
