# Generated by Django 2.0.4 on 2018-05-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0009_auto_20180505_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Profile Picture'),
        ),
    ]
